In [1]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
from csv import writer
import numpy as np
import re

## 1.Data Extraction

In [2]:
url= requests.get("https://www.jumia.co.ke/smartphones/?shipped_from=country_local#catalog-listing").text
soup=BeautifulSoup(url,'lxml')
item_list = soup.find_all('article',class_="prd _fb col c-prd",)

#item_list

for item in item_list:
    Productname= item.find('h3',class_='name')
    Price = item.find('div',class_='prc')
    print(Productname)
    print(Price)

<h3 class="name">Infinix Smart 6, 6.6", 2GB RAM, 32GB, 5000mAh,Polar Black</h3>
<div class="prc">KSh 10,299</div>
<h3 class="name">Tecno Pop 6 6.1", 2GB RAM+32GB, 8MP, 4G (Dual Sim) 5000MAh -Lime Green</h3>
<div class="prc">KSh 8,819</div>
<h3 class="name">XIAOMI Redmi 9A, 6.53", 2GB+32GB, 13.0MP, 5000mAh, 4G LTE, Dual SIM - Grey</h3>
<div class="prc">KSh 11,499</div>
<h3 class="name">Infinix Smart 6, 6.6", 32GB + 2GB RAM (Dual SIM), 5000mAh, Quartz Cyan</h3>
<div class="prc">KSh 10,696</div>
<h3 class="name">XIAOMI Redmi 10A, 6.53", 3GB+64GB, 13.0MP, 5000mAh, 4G LTE, Dual SIM - Graphite Grey</h3>
<div class="prc">KSh 14,799</div>
<h3 class="name">Oppo A16k, 6.52", 32GB + 3GB RAM (Dual SIM), 4230mAh - Blue</h3>
<div class="prc">KSh 14,278</div>
<h3 class="name">Oppo A83 64GB + 4GB RAM - 4G LTE Dual SIM -  5.7-inch,Red</h3>
<div class="prc">KSh 9,990</div>
<h3 class="name">XIAOMI Redmi 10 6.5'' Inches 4+128GB 50MP Rear Camera 4G Smartphone - Grey</h3>
<div class="prc">KSh 18,799</div>
<h3 class="name">Nokia C1 2nd Edition, 5.45", 1GB +16GB - (DUAL SIM),Android 11, Blue</h3>
<div class="prc">KSh 7,139</div>
<h3 class="name">Samsung Galaxy A13, 6.6", 64GB + 4GB RAM (Dual SIM), 5000mAh, Black</h3>
<div class="prc">KSh 19,299</div>
<h3 class="name">Tecno Pova Neo, 6.8", 64GB+ 4GB (Dual SIM),4G LTE, 6000mAh, Obsidian Black</h3>
<div class="prc">KSh 15,999</div>
<h3 class="name">Samsung Galaxy A13, 6.6", 64GB + 4GB RAM (Dual SIM), 5000mAh, Blue</h3>
<div class="prc">KSh 19,299</div>
<h3 class="name">Tecno Pop 6 GO, 6", 32GB + 2GB RAM ,(Dual SIM), 4000mAh,  + CLASSIC GIFTS</h3>
<div class="prc">KSh 9,445</div>
<h3 class="name">Samsung Galaxy A03s – 6.5″ – 32GB + 3GB – Dual SIM - Black</h3>
<div class="prc">KSh 13,699</div>
<h3 class="name">Samsung Galaxy A13, 6.6", 128GB + 4GB RAM (Dual SIM), 5000mAh, Black</h3>
<div class="prc">KSh 21,699</div>
<h3 class="name">Samsung Galaxy A03 Core, 6.5" 32GB + 2G, 5000mAh,Dual Sim- (Black) Onyx</h3>
<div class="prc">KSh 11,699</div>
<h3 class="name">Tecno CAMON 19, 6.8", 128GB+ 4GB (Dual SIM), (4G LTE) 5000mAh, Eco Black</h3>
<div class="prc">KSh 22,499</div>
<h3 class="name">XIAOMI Redmi 9C 6.53'', 4GB+128GB, 13MP+2MP+2MP Camera, 4G, Dual SIM - Lavender Purple</h3>
<div class="prc">KSh 16,299</div>
<h3 class="name">Oppo A83 64GB + 4GB RAM - 4G LTE Dual SIM -  5.7-inch,Black</h3>
<div class="prc">KSh 9,790</div>
<h3 class="name">Tecno CAMON 19, 6.8", 128GB+ 4GB (Dual SIM), (4G LTE) 5000mAh, Eco Black</h3>
<div class="prc">KSh 22,599</div>
<h3 class="name">Samsung Galaxy A23, 6.6″, 64GB + 4GB RAM (Dual SIM), 5000mAh, Blue</h3>
<div class="prc">KSh 22,499</div>
<h3 class="name">Itel A14 Plus, 4", 8GB + 1GB RAM, 2500mAh - Blue</h3>
<div class="prc">KSh 4,443</div>
<h3 class="name">Samsung Galaxy A03, 6.5", 64GB + 4GB RAM (Dual SIM), 5000mAh, Black</h3>
<div class="prc">KSh 15,299</div>
<h3 class="name">Infinix Smart 6, 6.6", 2GB RAM, 32GB, Android 10, XOS 7.6, 5000mAh, 3G - Ocean Wave</h3>
<div class="prc">KSh 10,695</div>
<h3 class="name">Infinix HOT 12i, 6.6''{ 64GB+2GB Expandable To 4GBRAM} (Dual SIM), 4G LTE, 5000mAh,black</h3>
<div class="prc">KSh 12,995</div>
<h3 class="name">Samsung Galaxy A03 6.5" 3GB RAM+32GB ROM 48 MP //Dual SIM-Blue+FREE EARBUDS+C+W</h3>
<div class="prc">KSh 13,990</div>
<h3 class="name">Tecno CAMON 19, 6.8", 128GB+ 4GB (Dual SIM), (4G LTE) 5000mAh, MEMPHIS GREEN</h3>
<div class="prc">KSh 22,846</div>
<h3 class="name">Ulefone Note 6, 6.1", 32GB + 1GB RAM (Dual SIM), 3300mAh, Black</h3>
<div class="prc">KSh 7,599</div>
<h3 class="name">XIAOMI Redmi 10C 6.71'', 4GB+128GB, 50MP+2MP Camera, 4G, Dual SIM - Blue</h3>
<div class="prc">KSh 19,099</div>
<h3 class="name">XIAOMI Redmi 9A 6.53", 2GB RAM+32GB, 5000mAh, Dual SIM, 4G LTE - Glacial Blue</h3>
<div class="prc">KSh 11,499</div>
<h3 class="name">Itel A58 Lite, 6.3", 32GB + 2GB RAM (Dual SIM), 4000mAh, Blue Wave</h3>
<div class="prc">KSh 8,255</div>
<h3 class="name">Itel A33 Plus,,5.0" Screen Display(16GB+1GB),Fingerprint,(Dual Sim) Blue,,w.s"</h3>
<div class="prc">KSh 6,160</div>
<h3 class="name">Samsung Galaxy A03, 6.5", 64GB + 4GB RAM (Dual SIM), 5000mAh, Blue</h3>
<div class="prc">KSh 15,299</div>
<h3 class="name">Infinix Smart 6, 6.6", 32GB + 2GB RAM (Dual SIM), 5000mAh +FREE GIFTS</h3>
<div class="prc">KSh 11,100</div>
<h3 class="name">Tecno Spark 9T, 6.6", (64GB ROM + 4GB RAM) , {Dual Sim} , 5000mAh, 4G, QUANTUM BLACK</h3>
<div class="prc">KSh 16,590</div>
<h3 class="name">Infinix Hot 12 Play, 6.82", 64GB + 4GB RAM (Dual SIM), 6000mAh, 4G - Horizon Blue</h3>
<div class="prc">KSh 15,950</div>
<h3 class="name">XIAOMI Redmi 10C 6.71'', 4GB+64GB, 50MP+2MP Camera, 4G, 5000MAH Battery Dual SIM- Blue</h3>
<div class="prc">KSh 16,499</div>
<h3 class="name">Tecno Spark 8C 6.6" 64GB+ 2GB RAM Dual Sim, Black + Smart Watch + P.Bank</h3>
<div class="prc">KSh 13,898</div>
<h3 class="name">Nokia G21 – 6.5″ – 128GB + 4GB – Dual SIM Nordic Blue</h3>
<div class="prc">KSh 18,900</div>
<h3 class="name">Samsung Galaxy A13, 6.6", 128GB + 4GB (Dual SIM), Blue + Smart Watch &amp; Power Bank</h3>
<div class="prc">KSh 22,997</div>

In [3]:
#To remove the html tags
all_items=[]

for item in item_list:
    Productname= item.find('h3',class_='name')
    Price = item.find('div',class_='prc')
    
    print(Productname.text.strip())
    print(Price.text.strip())
    all_items.append((Productname.text.strip(),Price.text.strip()))

Infinix Smart 6, 6.6", 2GB RAM, 32GB, 5000mAh,Polar Black
KSh 10,299
Tecno Pop 6 6.1", 2GB RAM+32GB, 8MP, 4G (Dual Sim) 5000MAh -Lime Green
KSh 8,819
XIAOMI Redmi 9A, 6.53", 2GB+32GB, 13.0MP, 5000mAh, 4G LTE, Dual SIM - Grey
KSh 11,499
Infinix Smart 6, 6.6", 32GB + 2GB RAM (Dual SIM), 5000mAh, Quartz Cyan
KSh 10,696
XIAOMI Redmi 10A, 6.53", 3GB+64GB, 13.0MP, 5000mAh, 4G LTE, Dual SIM - Graphite Grey
KSh 14,799
Oppo A16k, 6.52", 32GB + 3GB RAM (Dual SIM), 4230mAh - Blue
KSh 14,278
Oppo A83 64GB + 4GB RAM - 4G LTE Dual SIM -  5.7-inch,Red
KSh 9,990
XIAOMI Redmi 10 6.5'' Inches 4+128GB 50MP Rear Camera 4G Smartphone - Grey
KSh 18,799
Nokia C1 2nd Edition, 5.45", 1GB +16GB - (DUAL SIM),Android 11, Blue
KSh 7,139
Samsung Galaxy A13, 6.6", 64GB + 4GB RAM (Dual SIM), 5000mAh, Black
KSh 19,299
Tecno Pova Neo, 6.8", 64GB+ 4GB (Dual SIM),4G LTE, 6000mAh, Obsidian Black
KSh 15,999
Samsung Galaxy A13, 6.6", 64GB + 4GB RAM (Dual SIM), 5000mAh, Blue
KSh 19,299
Tecno Pop 6 GO, 6", 32GB + 2GB RAM ,(Dual SIM), 4000mAh,  + CLASSIC GIFTS
KSh 9,445
Samsung Galaxy A03s – 6.5″ – 32GB + 3GB – Dual SIM - Black
KSh 13,699
Samsung Galaxy A13, 6.6", 128GB + 4GB RAM (Dual SIM), 5000mAh, Black
KSh 21,699
Samsung Galaxy A03 Core, 6.5" 32GB + 2G, 5000mAh,Dual Sim- (Black) Onyx
KSh 11,699
Tecno CAMON 19, 6.8", 128GB+ 4GB (Dual SIM), (4G LTE) 5000mAh, Eco Black
KSh 22,499
XIAOMI Redmi 9C 6.53'', 4GB+128GB, 13MP+2MP+2MP Camera, 4G, Dual SIM - Lavender Purple
KSh 16,299
Oppo A83 64GB + 4GB RAM - 4G LTE Dual SIM -  5.7-inch,Black
KSh 9,790
Tecno CAMON 19, 6.8", 128GB+ 4GB (Dual SIM), (4G LTE) 5000mAh, Eco Black
KSh 22,599
Samsung Galaxy A23, 6.6″, 64GB + 4GB RAM (Dual SIM), 5000mAh, Blue
KSh 22,499
Itel A14 Plus, 4", 8GB + 1GB RAM, 2500mAh - Blue
KSh 4,443
Samsung Galaxy A03, 6.5", 64GB + 4GB RAM (Dual SIM), 5000mAh, Black
KSh 15,299
Infinix Smart 6, 6.6", 2GB RAM, 32GB, Android 10, XOS 7.6, 5000mAh, 3G - Ocean Wave
KSh 10,695
Infinix HOT 12i, 6.6''{ 64GB+2GB Expandable To 4GBRAM} (Dual SIM), 4G LTE, 5000mAh,black
KSh 12,995
Samsung Galaxy A03 6.5" 3GB RAM+32GB ROM 48 MP //Dual SIM-Blue+FREE EARBUDS+C+W
KSh 13,990
Tecno CAMON 19, 6.8", 128GB+ 4GB (Dual SIM), (4G LTE) 5000mAh, MEMPHIS GREEN
KSh 22,846
Ulefone Note 6, 6.1", 32GB + 1GB RAM (Dual SIM), 3300mAh, Black
KSh 7,599
XIAOMI Redmi 10C 6.71'', 4GB+128GB, 50MP+2MP Camera, 4G, Dual SIM - Blue
KSh 19,099
XIAOMI Redmi 9A 6.53", 2GB RAM+32GB, 5000mAh, Dual SIM, 4G LTE - Glacial Blue
KSh 11,499
Itel A58 Lite, 6.3", 32GB + 2GB RAM (Dual SIM), 4000mAh, Blue Wave
KSh 8,255
Itel A33 Plus,,5.0" Screen Display(16GB+1GB),Fingerprint,(Dual Sim) Blue,,w.s"
KSh 6,160
Samsung Galaxy A03, 6.5", 64GB + 4GB RAM (Dual SIM), 5000mAh, Blue
KSh 15,299
Infinix Smart 6, 6.6", 32GB + 2GB RAM (Dual SIM), 5000mAh +FREE GIFTS
KSh 11,100
Tecno Spark 9T, 6.6", (64GB ROM + 4GB RAM) , {Dual Sim} , 5000mAh, 4G, QUANTUM BLACK
KSh 16,590
Infinix Hot 12 Play, 6.82", 64GB + 4GB RAM (Dual SIM), 6000mAh, 4G - Horizon Blue
KSh 15,950
XIAOMI Redmi 10C 6.71'', 4GB+64GB, 50MP+2MP Camera, 4G, 5000MAH Battery Dual SIM- Blue
KSh 16,499
Tecno Spark 8C 6.6" 64GB+ 2GB RAM Dual Sim, Black + Smart Watch + P.Bank
KSh 13,898
Nokia G21 – 6.5″ – 128GB + 4GB – Dual SIM Nordic Blue
KSh 18,900
Samsung Galaxy A13, 6.6", 128GB + 4GB (Dual SIM), Blue + Smart Watch & Power Bank
KSh 22,997

In [4]:
#To put the data in a dataframe
df = pd.DataFrame(all_items)
df.columns = ["name", "price"]
df.to_csv('jumia_dataframe.csv')

## 2.Data Assesment

In [5]:
df.head()

                                                name       price
0  Infinix Smart 6, 6.6", 2GB RAM, 32GB, 5000mAh,...  KSh 10,299
1  Tecno Pop 6 6.1", 2GB RAM+32GB, 8MP, 4G (Dual ...   KSh 8,819
2  XIAOMI Redmi 9A, 6.53", 2GB+32GB, 13.0MP, 5000...  KSh 11,499
3  Infinix Smart 6, 6.6", 32GB + 2GB RAM (Dual SI...  KSh 10,696
4  XIAOMI Redmi 10A, 6.53", 3GB+64GB, 13.0MP, 500...  KSh 14,799

In [6]:
df.tail()

                                                 name       price
35  Infinix Hot 12 Play, 6.82", 64GB + 4GB RAM (Du...  KSh 15,950
36  XIAOMI Redmi 10C 6.71'', 4GB+64GB, 50MP+2MP Ca...  KSh 16,499
37  Tecno Spark 8C 6.6" 64GB+ 2GB RAM Dual Sim, Bl...  KSh 13,898
38  Nokia G21 – 6.5″ – 128GB + 4GB – Dual SIM Nord...  KSh 18,900
39  Samsung Galaxy A13, 6.6", 128GB + 4GB (Dual SI...  KSh 22,997

In [7]:
df.isna().sum()

name     0
price    0
dtype: int64

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    40 non-null     object
 1   price   40 non-null     object
dtypes: object(2)
memory usage: 768.0+ bytes

In [9]:
df.duplicated().sum()

0

## 3.Data Cleaning

1.To remove the 'ksh'symbol in the price column and to change the datatype to integer

In [10]:
df['price'] = df['price'].str[3:] 
df['price'] = df['price'].str.replace(',', '')
df['price'] = df['price'].astype(int)
df['price'].dtype

dtype('int32')

In [11]:
df['price'].tail()

35    15950
36    16499
37    13898
38    18900
39    22997
Name: price, dtype: int32

## 4.Feature Extraction

In [12]:
import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\kibe\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

Function to extract brand name

In [13]:

product_brands=['infinix','xiaomi','oppo','tecno','samsung','nokia','itel','ulefone']

def getbrand(name):
    name = name.lower()
    word_tokens= word_tokenize(name)
    brand = [char for char in word_tokens if char in product_brands]
    return ''.join(brand)

In [14]:
df['brand']=df['name'].apply(getbrand)

In [15]:
df.sample(10)

                                                 name  price    brand
19  Tecno CAMON 19, 6.8", 128GB+ 4GB (Dual SIM), (...  22599    tecno
38  Nokia G21 – 6.5″ – 128GB + 4GB – Dual SIM Nord...  18900    nokia
22  Samsung Galaxy A03, 6.5", 64GB + 4GB RAM (Dual...  15299  samsung
33  Infinix Smart 6, 6.6", 32GB + 2GB RAM (Dual SI...  11100  infinix
9   Samsung Galaxy A13, 6.6", 64GB + 4GB RAM (Dual...  19299  samsung
29  XIAOMI Redmi 9A 6.53", 2GB RAM+32GB, 5000mAh, ...  11499   xiaomi
39  Samsung Galaxy A13, 6.6", 128GB + 4GB (Dual SI...  22997  samsung
0   Infinix Smart 6, 6.6", 2GB RAM, 32GB, 5000mAh,...  10299  infinix
37  Tecno Spark 8C 6.6" 64GB+ 2GB RAM Dual Sim, Bl...  13898    tecno
31  Itel A33 Plus,,5.0" Screen Display(16GB+1GB),F...   6160     itel

Function to extract RAM

In [16]:
 df['name']=df['name'].str.replace('+',' ',regex=True)

In [17]:

ram_type=['1gb','2gb','3gb','4gb','2g']

def getram(name):
    name = name.lower()
    word_tokens= word_tokenize(name)
    ram = [char for char in word_tokens if char in ram_type]
    return ''.join(ram)
df['ram'] = df['name'].apply(getram)
df['ram'] = df['ram'].str[:-2]
df.sample(10)

                                                 name  price    brand ram
1   Tecno Pop 6 6.1", 2GB RAM 32GB, 8MP, 4G (Dual ...   8819    tecno   2
38  Nokia G21 – 6.5″ – 128GB   4GB – Dual SIM Nord...  18900    nokia   4
2   XIAOMI Redmi 9A, 6.53", 2GB 32GB, 13.0MP, 5000...  11499   xiaomi   2
37  Tecno Spark 8C 6.6" 64GB  2GB RAM Dual Sim, Bl...  13898    tecno   2
25  Samsung Galaxy A03 6.5" 3GB RAM 32GB ROM 48 MP...  13990  samsung   3
10  Tecno Pova Neo, 6.8", 64GB  4GB (Dual SIM),4G ...  15999    tecno   4
29  XIAOMI Redmi 9A 6.53", 2GB RAM 32GB, 5000mAh, ...  11499   xiaomi   2
12  Tecno Pop 6 GO, 6", 32GB   2GB RAM ,(Dual SIM)...   9445    tecno   2
20  Samsung Galaxy A23, 6.6″, 64GB   4GB RAM (Dual...  22499  samsung   4
22  Samsung Galaxy A03, 6.5", 64GB   4GB RAM (Dual...  15299  samsung   4

In [18]:
phone_storage=['8gb','16gb','32gb','64gb','128gb']

def getstorage(name):
    name = name.lower()
    word_tokens= word_tokenize(name)
    storage = [char for char in word_tokens if char in phone_storage]
    return ''.join(storage)
df['storage'] = df['name'].apply(getstorage)
df['storage'] = df['storage'].str[:-2]

df.sample(5)

,name,price,brand,ram,storage
8,"Nokia C1 2nd Edition, 5.45"", 1GB 16GB - (DUAL...",7139,nokia,1,16
5,"Oppo A16k, 6.52"", 32GB 3GB RAM (Dual SIM), 4...",14278,oppo,3,32
39,"Samsung Galaxy A13, 6.6"", 128GB 4GB (Dual SI...",22997,samsung,4,128
18,Oppo A83 64GB 4GB RAM - 4G LTE Dual SIM - 5...,9790,oppo,4,64
23,"Infinix Smart 6, 6.6"", 2GB RAM, 32GB, Android ...",10695,infinix,2,32

In [19]:
 #df['name']=df['name'].str.replace('()','')
#df

In [27]:
sim_type=['dual']

def getsim(name):
    name = name.lower()
    word_tokens= word_tokenize(name)
    sim = [char for char in word_tokens if char in sim_type]
    return ''.join(sim)
df['sim'] = df['name'].apply(getsim)
#df['sim'.replace('', np.nan)
#df['sim']= df['sim']fillna("single", inplace = True)
df

,name,price,brand,ram,storage,sim
0,"Infinix Smart 6, 6.6"", 2GB RAM, 32GB, 5000mAh,...",10299,infinix,2,32,
1,"Tecno Pop 6 6.1"", 2GB RAM 32GB, 8MP, 4G (Dual ...",8819,tecno,2,32,dual
2,"XIAOMI Redmi 9A, 6.53"", 2GB 32GB, 13.0MP, 5000...",11499,xiaomi,2,32,dual
3,"Infinix Smart 6, 6.6"", 32GB 2GB RAM (Dual SI...",10696,infinix,2,32,dual
4,"XIAOMI Redmi 10A, 6.53"", 3GB 64GB, 13.0MP, 500...",14799,xiaomi,3,64,dual
5,"Oppo A16k, 6.52"", 32GB 3GB RAM (Dual SIM), 4...",14278,oppo,3,32,dual
6,Oppo A83 64GB 4GB RAM - 4G LTE Dual SIM - 5...,9990,oppo,4,64,dual
7,XIAOMI Redmi 10 6.5'' Inches 4 128GB 50MP Rear...,18799,xiaomi,,128,
8,"Nokia C1 2nd Edition, 5.45"", 1GB 16GB - (DUAL...",7139,nokia,1,16,dual
9,"Samsung Galaxy A13, 6.6"", 64GB 4GB RAM (Dual...",19299,samsung,4,64,dual
10,"Tecno Pova Neo, 6.8"", 64GB 4GB (Dual SIM),4G ...",15999,tecno,4,64,dual
11,"Samsung Galaxy A13, 6.6"", 64GB 4GB RAM (Dual...",19299,samsung,4,64,dual
12,"Tecno Pop 6 GO, 6"", 32GB 2GB RAM ,(Dual SIM)...",9445,tecno,2,32,dual
13,Samsung Galaxy A03s – 6.5″ – 32GB 3GB – Dual...,13699,samsung,3,32,dual
14,"Samsung Galaxy A13, 6.6"", 128GB 4GB RAM (Dua...",21699,samsung,4,128,dual
15,"Samsung Galaxy A03 Core, 6.5"" 32GB 2G, 5000m...",11699,samsung,,32,dual
16,"Tecno CAMON 19, 6.8"", 128GB 4GB (Dual SIM), (...",22499,tecno,4,128,dual
17,"XIAOMI Redmi 9C 6.53'', 4GB 128GB, 13MP 2MP 2M...",16299,xiaomi,4,128,dual
18,Oppo A83 64GB 4GB RAM - 4G LTE Dual SIM - 5...,9790,oppo,4,64,dual
19,"Tecno CAMON 19, 6.8"", 128GB 4GB (Dual SIM), (...",22599,tecno,4,128,dual
20,"Samsung Galaxy A23, 6.6″, 64GB 4GB RAM (Dual...",22499,samsung,4,64,dual
21,"Itel A14 Plus, 4"", 8GB 1GB RAM, 2500mAh - Blue",4443,itel,1,8,
22,"Samsung Galaxy A03, 6.5"", 64GB 4GB RAM (Dual...",15299,samsung,4,64,dual
23,"Infinix Smart 6, 6.6"", 2GB RAM, 32GB, Android ...",10695,infinix,2,32,
24,"Infinix HOT 12i, 6.6''{ 64GB 2GB Expandable To...",12995,infinix,2,64,dual
25,"Samsung Galaxy A03 6.5"" 3GB RAM 32GB ROM 48 MP...",13990,samsung,3,32,
26,"Tecno CAMON 19, 6.8"", 128GB 4GB (Dual SIM), (...",22846,tecno,4,128,dual
27,"Ulefone Note 6, 6.1"", 32GB 1GB RAM (Dual SIM...",7599,ulefone,1,32,dual
28,"XIAOMI Redmi 10C 6.71'', 4GB 128GB, 50MP 2MP C...",19099,xiaomi,4,128,dual
29,"XIAOMI Redmi 9A 6.53"", 2GB RAM 32GB, 5000mAh, ...",11499,xiaomi,2,32,dual
30,"Itel A58 Lite, 6.3"", 32GB 2GB RAM (Dual SIM)...",8255,itel,2,32,dual
31,"Itel A33 Plus,,5.0"" Screen Display(16GB 1GB),F...",6160,itel,1,16,dual
32,"Samsung Galaxy A03, 6.5"", 64GB 4GB RAM (Dual...",15299,samsung,4,64,dual
33,"Infinix Smart 6, 6.6"", 32GB 2GB RAM (Dual SI...",11100,infinix,2,32,dual
34,"Tecno Spark 9T, 6.6"", (64GB ROM 4GB RAM) , {...",16590,tecno,4,64,dual
35,"Infinix Hot 12 Play, 6.82"", 64GB 4GB RAM (Du...",15950,infinix,4,64,dual
36,"XIAOMI Redmi 10C 6.71'', 4GB 64GB, 50MP 2MP Ca...",16499,xiaomi,4,64,dual
37,"Tecno Spark 8C 6.6"" 64GB 2GB RAM Dual Sim, Bl...",13898,tecno,2,64,dual
38,Nokia G21 – 6.5″ – 128GB 4GB – Dual SIM Nord...,18900,nokia,4,128,dual
39,"Samsung Galaxy A13, 6.6"", 128GB 4GB (Dual SI...",22997,samsung,4,128,dual